### ISSUE TITLE
Dependencies / platform issues

### ISSUE THREAD

**Issue by gaamaaresosa** [n4sm/m0dern_p4cker#1]
Where to go for this libelf.h ?

```
 $ sudo chmod +x make.sh && sudo ./make.sh
packer.c:21:10: fatal error: libelf.h: No such file or directory
 #include <libelf.h>
          ^~~~~~~~~~
compilation terminated.
packer_functions.c:4:10: fatal error: libelf.h: No such file or directory
 #include <libelf.h>
          ^~~~~~~~~~
compilation terminated.
[*] test and main has been generated

```

**Comment by n4sm** [comment]
You can get it from your package manager, for example on ubuntu:
```bash
sudo apt update
sudo apt install libelf-dev
```

**Comment by gaamaaresosa** [comment]
> You can get it from your package manager, for example on ubuntu:
> 
> ```shell
> sudo apt update
> sudo apt install libelf-dev
> ```

Thanks you so much !
Is this project works now on the latest linux on Raspberry Pi 4 ?
I tried and left it because it seems incomplete or very old version.

Note: Please always release the requirement.txt file for dependencies.
Intermediate linux knowledged persons like me will have tough time then.

**Comment by n4sm** [comment]
It does work only on x86-based platforms given I use specific intel assembly stubs to unpack the binaries.
